[mongodb]
uri = "mongodb+srv://hamza:hamza123@cluster0.bulzdjl.mongodb.net/Binance?retryWrites=true&w=majority&appName=Cluster0"

[binance]
api_key = "VKuSdnSh1LK2apOk0dSaRHPvgoNcv2DpzL205A1MgA2KksTRV6FtfbPKQa4Vzq4z"
api_secret = "E6xR3mJDdknnmL2VDftz1sBpDFIUZ1EaREr6Nf14PYQ3vcg2fMNoIUNQrGZ03joo"
[forex]
api_key = "AR   NDG9VMQFY6M0XK"